services:
    core:
        build: core
        image: reader-core
        ports:
            - "9495:9494"
        volumes:
            - type: bind
              source: ./data
              target: /app/data
            - ${PWD}/config.toml:/app/config.toml
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
    web:
        build: web
        image: reader-web
        ports:
            - "5050:3030"
        volumes:
            - type: bind
              source: ./data
              target: /app/data
            - ${PWD}/config.toml:/app/config.toml
